Stop altering default last post info
brunoais/phpbbextf_read_other pull request #17
Opened 2019-03-05 12:41 UTC by Dezash

Currently, if you disable "Can read forum" permission, this extension will hide last post info even if "Can read topics started by others" is set to Yes. Since I have some forums which cannot be read by guests, I noticed that this extension replaces last post info with "Classified information". I suppose that by design setting "Can read topics started by others" to yes should mean that default behavior is not altered.

Before:
![before](https://user-images.githubusercontent.com/11979849/53806068-9c15fc00-3f54-11e9-993a-7df62f3905d6.PNG)
After:
![after](https://user-images.githubusercontent.com/11979849/53806070-9e785600-3f54-11e9-9b7f-f0b459fb8e46.PNG)

This PR also fixes incorrectly placed language files which prevented the permissions tab in ACP from working.

2019-03-05 18:34 UTC, brunoais commented
> Currently, if you disable "Can read forum" permission, this extension will hide last post info even if "Can read topics started by others" is set to Yes
That is by design. If you cannot read the forum, you cannot see anything so "Can read topics started by others" becomes useless if you set "Can read forum" to `no`

Are you able to see anything in the forum if you set "Can read forum" to `no`?

2019-03-08 15:58 UTC, Dezash commented
By default, if you set "Can read forum" to no, you can still see the last post info, however this behavior is altered by the extension.

2019-03-08 19:17 UTC, brunoais requested changes
Final changes

2019-03-08 19:17 UTC, brunoais commented on event/main_listener.php
> -		));
Do not delete permission_evaluate please.

2019-03-08 19:17 UTC, brunoais commented on event/main_listener.php
> +		if (!$this->auth->acl_get('f_read_others_topics_brunoais', $event['row']['forum_id']))
make use of `accesses::NO_READ_OTHER` instead please.

2019-03-08 19:17 UTC, brunoais approved these changes

2019-03-08 19:18 UTC, merged

2019-03-08 19:18 UTC, brunoais commented
Thank you